<template>
  <v-container>
    <v-row>
      <v-col>
        <v-card class="mx-auto" max-width="344">
          <div class="margin">
          </div>
          <v-img src="https://fightingsou.github.io/images/works.png" height="270px" cover></v-img>
          <div class="margin">
          </div>
        </v-card>
      </v-col>
      <v-col>
        <v-card class="mx-auto" max-width="344">
          <v-img src="https://fightingsou.github.io/images/portfolio.png" height="150px" cover></v-img>
          <v-card-title>
            Portfolio Site
          </v-card-title>
          <v-card-subtitle>
            Here.
            <br>
            <br>
          </v-card-subtitle>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn
              :icon="show1 ? 'mdi-chevron-up' : 'mdi-chevron-down'"
              @click="show1 = !show1"
            ></v-btn>
          </v-card-actions>
          <v-expand-transition>
            <div v-show="show1">
              <v-divider></v-divider>
              <v-card-text>
                This is my portfolio site, created using Vue.js.<br>
                <a href="https://github.com/fightingsou/my-portfolio/tree/master">GitHub</a>
              </v-card-text>
            </div>
          </v-expand-transition>
        </v-card>
      </v-col>
      <v-col>
        <v-card class="mx-auto" max-width="344">
          <v-img src="https://fightingsou.github.io/images/mosac.jpg" height="150px" cover></v-img>
          <v-card-title>
            Mosaic Art Generator
          </v-card-title>
          <v-card-subtitle>
            Mosaic art generation by<br>symbiotic evolution.
          </v-card-subtitle>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn
              :icon="show2 ? 'mdi-chevron-up' : 'mdi-chevron-down'"
              @click="show2 = !show2"
            ></v-btn>
          </v-card-actions>
          <v-expand-transition>
            <div v-show="show2">
              <v-divider></v-divider>
              <v-card-text>
                Received an award of excellence at 5th TCU R-PresCo.<br>
                For students who have no memorable photos due to the Corona Disaster, images are generated by Stable Diffusion, and mosaic art is generated by Symbiotic Evolution.<br>
                <a href="https://github.com/otanilab/R-PresCo2022">GitHub</a>
                <a> | </a>
                <a href="https://informatics.tcu.ac.jp/news/award/?&p=841">News</a>
              </v-card-text>
            </div>
          </v-expand-transition>
        </v-card>
      </v-col>
    </v-row>
    <v-row>
      <v-col>
        <v-card class="mx-auto" max-width="344">
          <v-img src="https://fightingsou.github.io/images/thinker.jpg" height="150px" cover></v-img>
          <v-card-title>
            The Thinker
          </v-card-title>
          <v-card-subtitle>
            A web application for environmental<br>
            issues.
          </v-card-subtitle>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn
              :icon="show3 ? 'mdi-chevron-up' : 'mdi-chevron-down'"
              @click="show3 = !show3"
            ></v-btn>
          </v-card-actions>
          <v-expand-transition>
            <div v-show="show3">
              <v-divider></v-divider>
              <v-card-text>
                A web application that aims to raise questions about current perceptions of environmental issues.
                The presentation won the third place in the SD PBL course held at the university.
                Developed with Nuxt.js.<br>
                <a href="https://github.com/fightingsou/the-thinker">GitHub</a>
              </v-card-text>
            </div>
          </v-expand-transition>
        </v-card>
      </v-col>
      <v-col>
        <v-card class="mx-auto" max-width="344">
          <v-img src="https://fightingsou.github.io/images/yoshida.jpg" height="150px" cover></v-img>
          <v-card-title>
            OK Yoshida
          </v-card-title>
          <v-card-subtitle>
            Watering management LINE bot for<br>
            houseplants.
          </v-card-subtitle>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn
              :icon="show4 ? 'mdi-chevron-up' : 'mdi-chevron-down'"
              @click="show4 = !show4"
            ></v-btn>
          </v-card-actions>
          <v-expand-transition>
            <div v-show="show4">
              <v-divider></v-divider>
              <v-card-text>
                A watering management LINE bot for houseplants developed with Google App Script.<br>
                <a href="https://github.com/fightingsou/ok-yoshida">GitHub</a>
              </v-card-text>
            </div>
          </v-expand-transition>
        </v-card>
      </v-col>
      <v-col>
        <v-card class="mx-auto" max-width="344">
          <v-img src="https://fightingsou.github.io/images/outing.png" height="150px" cover></v-img>
          <v-card-title>
            Outing Support App
          </v-card-title>
          <v-card-subtitle>
            Android apps to help you go out.
            <br>
            <br>
          </v-card-subtitle>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn
              :icon="show5 ? 'mdi-chevron-up' : 'mdi-chevron-down'"
              @click="show5 = !show5"
            ></v-btn>
          </v-card-actions>
          <v-expand-transition>
            <div v-show="show5">
              <v-divider></v-divider>
              <v-card-text>
                An outing support application created in a university lecture, developed jointly by three students, and received the best grade.
                Developed with Android Studio.<br>
                <a href="https://github.com/fightingsou/outing-support-app">GitHub</a>
              </v-card-text>
            </div>
          </v-expand-transition>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  name: 'Works',
  data: () => ({
    show1: false,
    show2: false,
    show3: false,
    show4: false,
    show5: false,
  }),
}
</script>

<style lang="scss" scoped>
.v-card {
  width: 300px;
  margin-top: 40px;
  box-shadow: 0 1px 2px 2px rgba(0, 0, 0, 0.1);
  .margin {
    margin-top: 15.5px;
  }
  a {
    text-decoration: none;
    color: #3f51b5;
  }
}
</style>
